config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :books
  resources :borrowings
  get 'dashboard/librarian', to: 'dashboards#librarian', as: :librarian_dashboard
  get 'dashboard/member', to: 'dashboards#member', as: :member_dashboard
  root 'books#index'
  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord
  has_many :borrowings
  has_many :users, through: :borrowings

  validates :title, presence: true
  validates :author, presence: true
  validates :isbn, presence: true, uniqueness: true
  validates :total_copies, presence: true, numericality: { greater_than_or_equal_to: 1 }

  def available?
    total_copies - borrowings.count > 0
  end
end

app/models/borrowing.rb
class Borrowing < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validates :user_id, presence: true
  validates :book_id, presence: true
  validates :borrowed_on, presence: true
  validates :due_on, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  enum role: { member: 0, librarian: 1 }
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :borrowings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_book, only: [:show, :edit, :update, :destroy]
  before_action :authorize_book, except: %i[index show search]

  # GET /books or /books.json
  def index
    @books = Book.all

    respond_to do |format|
      format.html # renders index.html.erb
      format.json { render json: @books }
    end
  end

   # GET /books/1 or /books/1.json
   def show
    respond_to do |format|
      format.html # renders show.html.erb
      format.json { render json: @book }
    end
  end

  def new
    @book = Book.new
  end

  def edit; end

  # POST /books or /books.json
  def create
    @book = Book.new(book_params)
    authorize @book

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render json: @book, status: :created }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1 or /books/1.json
  def update
    authorize @book
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render json: @book, status: :ok }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1 or /books/1.json
  def destroy
    authorize @book
    @book.destroy

    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def search
    @books = Book.where('title LIKE ? OR author LIKE ? OR genre LIKE ?', "%#{params[:query]}%", "%#{params[:query]}%", "%#{params[:query]}%")

    respond_to do |format|
      format.html # renders search.html.erb
      format.json { render json: @books }
    end
  end

  private

  def set_book
    @book = Book.find(params[:id])
  end

  def authorize_book
    authorize @book
  end

  def book_params
    params.require(:book).permit(:title, :author, :genre, :isbn, :total_copies)
  end
end

app/controllers/borrowings_controller.rb
class BorrowingsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_borrowing, only: %i[update]

  def index
    @borrowings = Borrowing.all
    authorize @borrowings
  end

  def new
    @borrowing = Borrowing.new
    authorize_borrowing
  end

  def edit
  end

  def create
    @borrowing = current_user.borrowings.build(borrowing_params)
    authorize_borrowing

    if @borrowing.save
      redirect_to @borrowing.book, notice: 'Book was successfully borrowed.'
    else
      redirect_to @borrowing.book, alert: 'Unable to borrow book.'
    end
  end

  def update
    if @borrowing.update(returned_on: Date.today)
      redirect_to @borrowing.book, notice: 'Book was successfully returned.'
    else
      redirect_to @borrowing.book, alert: 'Unable to return book.'
    end
  end

  private

  def set_borrowing
    @borrowing = Borrowing.find(params[:id])
  end

  def authorize_borrowing
    authorize @borrowing
  end

  def borrowing_params
    params.require(:borrowing).permit(:book_id).merge(borrowed_on: Date.today, due_on: 2.weeks.from_now)
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  before_action :authenticate_user!

  def librarian
    @total_books = Book.count
    @total_borrowed_books = Borrowing.where(returned_on: nil).count
    @books_due_today = Borrowing.where(due_on: Date.today, returned_on: nil)
    @overdue_books = Borrowing.where('due_on < ? AND returned_on IS NULL', Date.today)
  end

  def member
    @borrowings = current_user.borrowings
    @overdue_books = current_user.borrowings.where('due_on < ? AND returned_on IS NULL', Date.today)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/borrowings_helper.rb
module BorrowingsHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/views/books/_form.html.erb
<%= form_with(model: book, local: true) do |form| %>
  <% if book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>
      <ul>
        <% book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :author %>
    <%= form.text_field :author, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :genre %>
    <%= form.text_field :genre, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :isbn %>
    <%= form.text_field :isbn, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :total_copies %>
    <%= form.number_field :total_copies, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Edit Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Back', book_path(@book), class: 'btn btn-secondary' %>

app/views/books/index.html.erb
<h1>Books</h1>

<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Author</th>
      <th>Genre</th>
      <th>ISBN</th>
      <th>Total Copies</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.title %></td>
        <td><%= book.author %></td>
        <td><%= book.genre %></td>
        <td><%= book.isbn %></td>
        <td><%= book.total_copies %></td>
        <td>
          <%= link_to 'Show', book_path(book), class: 'btn btn-info' %>
          <% if current_user.librarian? %>
            <%= link_to 'Edit', edit_book_path(book), class: 'btn btn-warning' %>
            <%= link_to 'Delete', book_path(book), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<% if current_user.librarian? %>
  <%= link_to 'New Book', new_book_path, class: 'btn btn-primary' %>
<% end %>

app/views/books/new.html.erb
<h1>New Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Back', books_path, class: 'btn btn-secondary' %>

app/views/books/show.html.erb
<h1><%= @book.title %></h1>

<p>
  <strong>Author:</strong>
  <%= @book.author %>
</p>

<p>
  <strong>Genre:</strong>
  <%= @book.genre %>
</p>

<p>
  <strong>ISBN:</strong>
  <%= @book.isbn %>
</p>

<p>
  <strong>Total Copies:</strong>
  <%= @book.total_copies %>
</p>

<% if current_user.librarian? %>
  <%= link_to 'Edit', edit_book_path(@book), class: 'btn btn-warning' %>
  <%= link_to 'Back', books_path, class: 'btn btn-secondary' %>
  <%= link_to 'Delete', book_path(@book), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
<% else %>
  <%= link_to 'Back', books_path, class: 'btn btn-secondary' %>
<% end %>

app/views/borrowings/_from.html.erb
<%= form_with(model: borrowing, local: true) do |form| %>
  <% if borrowing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(borrowing.errors.count, "error") %> prohibited this borrowing from being saved:</h2>
      <ul>
        <% borrowing.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :book_id %>
    <%= form.collection_select :book_id, Book.all, :id, :title, include_blank: true, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :user_id %>
    <%= form.collection_select :user_id, User.all, :id, :email, include_blank: true, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :borrowed_on %>
    <%= form.date_select :borrowed_on, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :due_on %>
    <%= form.date_select :due_on, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :returned_on %>
    <%= form.date_select :returned_on, class: 'form-control', include_blank: true %>
  </div>

  <div class="actions">
    <%= form.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/borrowings/edit.html.erb
<h1>Edit Borrowing</h1>

<%= render 'form', borrowing: @borrowing %>

<%= link_to 'Back', borrowing_path(@borrowing), class: 'btn btn-secondary' %>

app/views/borrowings/index.html.erb
<h1>Borrowings</h1>

<table class="table">
  <thead>
    <tr>
      <th>Book</th>
      <th>User</th>
      <th>Borrowed On</th>
      <th>Due On</th>
      <th>Returned On</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @borrowings.each do |borrowing| %>
      <tr>
        <td><%= borrowing.book.title %></td>
        <td><%= borrowing.user.email %></td>
        <td><%= borrowing.borrowed_on %></td>
        <td><%= borrowing.due_on %></td>
        <td><%= borrowing.returned_on %></td>
        <td>
          <% if borrowing.returned_on.nil? && current_user.librarian? %>
            <%= link_to 'Mark as Returned', borrowing_path(borrowing), method: :put, class: 'btn btn-primary' %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/borrowings/new.html.erb
<h1>New Borrowing</h1>

<%= render 'form', borrowing: @borrowing %>

<%= link_to 'Back', borrowings_path, class: 'btn btn-secondary' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Library Management System</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="#">Library Management System</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ml-auto">
          <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to 'Books', books_path, class: 'nav-link' %>
            </li>
            <% if current_user.librarian? %>
              <li class="nav-item">
                <%= link_to 'Librarian Dashboard', librarian_dashboard_path, class: 'nav-link' %>
              </li>
            <% else %>
              <li class="nav-item">
                <%= link_to 'Member Dashboard', member_dashboard_path, class: 'nav-link' %>
              </li>
            <% end %>
            <li class="nav-item">
              <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: 'nav-link' %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to 'Login', new_user_session_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to 'Sign Up', new_user_registration_path, class: 'nav-link' %>
            </li>
          <% end %>
        </ul>
      </div>
    </nav>

    <div class="container mt-4">
      <% if notice %>
        <div class="alert alert-success"><%= notice %></div>
      <% end %>
      <% if alert %>
        <div class="alert alert-danger"><%= alert %></div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>